### PR TITLE
feat: Make boolean quirk an enum

### PR DESCRIPTION
**Pull request by provokateurin**
For query parameters we have to convert booleans into integers as they are only accepted that way. This sets the `enum` field on the returned integer schema to indicate that these are the only possible values.
Can be tested in the server.

### CODE REVIEW

**Comment by nickvergessen** [comment]
Conflicting files
src/OpenApiType.php

**Comment by provokateurin** [comment]
Fixed

**Review by nickvergessen — APPROVED** [review]
So at least bools only allow int with enum 0 and 1 now, so better than before.
But shouldn't it be listed as bool?

**Comment by provokateurin** [comment]
The problem is that query parameters are always interpreted as true unless the value is 0. So we need to map them as integers :/

**Comment by nickvergessen** [comment]
Added tests in https://github.com/nextcloud/openapi-extractor/pull/59

**Comment by nickvergessen** [comment]
> The problem is that query parameters are always interpreted as true unless the value is 0.

But not when you POST a JSON body, but it will work in both cases anyway, so okay

**Comment by provokateurin** [comment]
Yes with a json post body boolean works fine, but not with the query parameters as we use them here.

**Pull request merged**
