### PR TITLE
fix(OpenApiType): Forbid using ambigous array syntaxes

### PR DESCRIPTION
**Pull request by provokateurin**
Fixes https://github.com/nextcloud/openapi-extractor/issues/33

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Comment by provokateurin** [comment]
Server and notifications are green now, shall we merge and make a new release @nickvergessen?

**Comment by nickvergessen** [comment]
*/me stares at 140 complains for empty arrays in talk*

"Sure, let's go ahead"

**Comment by nickvergessen** [comment]
Maybe `array<empty>` can be handled as an exception?

**Comment by provokateurin** [comment]
> Maybe array<empty> can be handled as an exception and only yield a warning?

Could be added, but it's also very simple to fix with search and replace and there are no manual changes that need to be done.

**Pull request merged**
