### PR TITLE
Tests for "fix(parameters): Support int numerals #38"

### PR DESCRIPTION
**Pull request by nickvergessen**
- [ ] Fix extracted to #38  - This PR is kept to merge the tests ones the base is there
- [ ] Based on #59  for testing

Before | After
---|---
Bildschirmfoto vom 2023-11-10 12-48-43 | Bildschirmfoto vom 2023-11-10 12-48-09

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]
I wonder if it would be possible to merge this with the string enum handling to reduce duplicate code since they are both quite similar.

**Comment by nickvergessen** [comment]
I don't have a usecase atm, but i wonder what happens if you mix int+string on one parameter, will try after lunch

**Comment by provokateurin** [comment]
I think it should resort to using `oneOf`. Only string and int are enums that would make sense (boolean maybe too?)

**Comment by nickvergessen** [comment]
```
* @param 0|1|'yes'|'no'|true
```

You mean?

**Comment by provokateurin** [comment]
Yes, although now I'm not sure how it will handle it :sweat_smile:

**Comment by nickvergessen** [comment]
Let's move that to a follow up, as mixed types seem to not work at all:

```
* @param 0|1|'yes'|'no'|true $weird Weird list
```
Generates:
```
                    {
                        "name": "weird",
                        "in": "query",
                        "description": "Weird list",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
```

**Comment by provokateurin** [comment]
@nickvergessen can you set the target branch to the main branch and drop the scope commits so we can get this merged already?

**Comment by nickvergessen** [comment]
Well doesn't work with the test files.

I can make a new PR against master with only the source code, but we should keep a second PR/branch/commit to merge the tests as soon as that is possible.

**Comment by provokateurin** [comment]
Fine by me

**Comment by nickvergessen** [comment]
Test added in #59

**Pull request closed without merging**
